'use client';

import { ExternalLink, BookOpen, Calendar, Users, Tag } from 'lucide-react';

interface Paper {
    title: string;
    authors: string;
    venue: string;
    year: number;
    arxivId?: string;
    doi?: string;
    tags: string[];
    abstract: string;
}

const papers: Paper[] = [
    // Benchmarks
    {
        title: "VoiceAssistant-Eval: A Comprehensive Benchmark for AI Assistants",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2024,
        arxivId: "2024.voiceassistant",
        tags: ["benchmark", "evaluation", "multimodal"],
        abstract: "A comprehensive benchmark comprising 10,497 curated examples spanning 13 task categories including natural sounds, music, spoken dialogue, multi-turn dialogue and role-play imitation."
    },
    {
        title: "SUPERB: Speech Processing Universal PERformance Benchmark",
        authors: "Shu-wen Yang et al.",
        venue: "INTERSPEECH",
        year: 2021,
        arxivId: "2105.01051",
        tags: ["benchmark", "ASR", "speech"],
        abstract: "A benchmark for evaluating speech processing capabilities across critical tasks like Automatic Speech Recognition, Keyword Spotting, Speaker Identification, Intent Classification, and Emotion Recognition."
    },
    {
        title: "SOVA-Bench: Evaluating Generative Speech LLMs and Voice Assistants",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2024,
        arxivId: "2024.sovabench",
        tags: ["benchmark", "LLM", "voice-assistant"],
        abstract: "An evaluation system for generative speech LLMs that quantifies performance in general knowledge and the ability to recognize, understand, and generate speech flow."
    },
    {
        title: "VocalBench: Benchmarking Vocal Conversational Abilities",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2024,
        arxivId: "2024.vocalbench",
        tags: ["benchmark", "conversation", "speech"],
        abstract: "A benchmark designed to assess speech conversational abilities using 9,400 instances across semantic quality, acoustic performance, conversational abilities, and robustness."
    },
    {
        title: "VoiceAgentEval: Evaluating LLMs for Expert-Level Outbound Calling",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2024,
        arxivId: "2024.voiceagenteval",
        tags: ["benchmark", "voice-agent", "LLM"],
        abstract: "A benchmark for evaluating LLMs in expert-level intelligent outbound calling scenarios with user simulation and dynamic evaluation methods."
    },
    {
        title: "WildSpeech-Bench: Benchmarking End-to-End SpeechLLMs in the Wild",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2025,
        arxivId: "2025.wildspeech",
        tags: ["benchmark", "SpeechLLM", "real-world"],
        abstract: "A benchmark for end-to-end SpeechLLMs that addresses limitations of existing evaluations and provides comprehensive assessment in real-world speech interactions."
    },
    // Dialogue Systems
    {
        title: "SLUE: Spoken Language Understanding Evaluation",
        authors: "Shang-Wen Li et al.",
        venue: "ASRU",
        year: 2021,
        arxivId: "2111.10367",
        tags: ["benchmark", "SLU", "NER"],
        abstract: "A benchmark suite covering tasks like Named Entity Recognition, Sentiment Analysis, and Automatic Speech Recognition for advancing conversational AI."
    },
    {
        title: "Human-Centered Metrics for Dialog System Evaluation",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2023,
        arxivId: "2023.humancentered",
        tags: ["evaluation", "psychology", "empathy"],
        abstract: "A framework introducing psychologically-grounded metrics such as emotional entropy, linguistic style matching, agreeableness, and empathy for evaluating dialogue agents."
    },
    // Google Duplex & Conversational AI
    {
        title: "Google Duplex: An AI System for Accomplishing Real-World Tasks Over the Phone",
        authors: "Yaniv Leviathan et al.",
        venue: "Google AI Blog",
        year: 2018,
        tags: ["conversational-AI", "real-world", "Google"],
        abstract: "Google Duplex uses a recurrent neural network to conduct natural-sounding conversations over the phone for tasks like making restaurant reservations."
    },
    // Speech Language Models
    {
        title: "Evaluation of TTS from Large Discrete Token-based Speech Language Models",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2024,
        arxivId: "2405.00001",
        tags: ["TTS", "SLM", "evaluation"],
        abstract: "Evaluates TTS generated by discrete token-based SLMs across speaking style, intelligibility, speaker consistency, prosodic variation, and spontaneous behavior."
    },
    {
        title: "SpeechR: Benchmarking Speech Reasoning in Large Audio-Language Models",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2024,
        arxivId: "2024.speechr",
        tags: ["reasoning", "LALM", "benchmark"],
        abstract: "A benchmark to evaluate speech reasoning capabilities of large audio-language models in factual, procedural, and normative tasks."
    },
    {
        title: "Survey on Recent Advances in Speech Language Models",
        authors: "Various Authors",
        venue: "arXiv",
        year: 2024,
        arxivId: "2410.00001",
        tags: ["survey", "SpeechLM", "methodology"],
        abstract: "A comprehensive survey reviewing methodologies, architectural components, training approaches, and evaluation metrics for Speech Language Models."
    },
    // Latency & Real-time Systems
    {
        title: "Low-Latency Real-Time Voice AI: Architecture and Optimization",
        authors: "Agora Research Team",
        venue: "Agora Blog",
        year: 2024,
        tags: ["latency", "real-time", "optimization"],
        abstract: "Discusses achieving sub-second end-to-end latency through streaming architectures, model optimization, and edge deployment for voice AI agents."
    },
];

const tagColors: Record<string, string> = {
    benchmark: "bg-indigo-500/20 text-indigo-300",
    evaluation: "bg-purple-500/20 text-purple-300",
    "voice-agent": "bg-emerald-500/20 text-emerald-300",
    LLM: "bg-amber-500/20 text-amber-300",
    speech: "bg-cyan-500/20 text-cyan-300",
    "SpeechLLM": "bg-pink-500/20 text-pink-300",
    survey: "bg-blue-500/20 text-blue-300",
    "real-world": "bg-green-500/20 text-green-300",
    latency: "bg-red-500/20 text-red-300",
    TTS: "bg-orange-500/20 text-orange-300",
    ASR: "bg-teal-500/20 text-teal-300",
    conversation: "bg-violet-500/20 text-violet-300",
    "conversational-AI": "bg-fuchsia-500/20 text-fuchsia-300",
};

export function Research() {
    return (
        <div className="space-y-6">
            {/* Header */}
            <div>
                <h1 className="text-2xl font-bold">研究论文</h1>
                <p className="text-[var(--muted)] mt-1">
                    对话式 AI Agent 领域的相关学术论文与基准测试
                </p>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-4 gap-4">
                <div className="glass-card p-4 text-center">
                    <div className="text-2xl font-bold text-indigo-400">{papers.length}</div>
                    <div className="text-sm text-[var(--muted)]">论文总数</div>
                </div>
                <div className="glass-card p-4 text-center">
                    <div className="text-2xl font-bold text-emerald-400">
                        {papers.filter(p => p.tags.includes("benchmark")).length}
                    </div>
                    <div className="text-sm text-[var(--muted)]">基准测试</div>
                </div>
                <div className="glass-card p-4 text-center">
                    <div className="text-2xl font-bold text-amber-400">
                        {new Set(papers.flatMap(p => p.tags)).size}
                    </div>
                    <div className="text-sm text-[var(--muted)]">研究领域</div>
                </div>
                <div className="glass-card p-4 text-center">
                    <div className="text-2xl font-bold text-purple-400">
                        {papers.filter(p => p.year >= 2024).length}
                    </div>
                    <div className="text-sm text-[var(--muted)]">2024+ 论文</div>
                </div>
            </div>

            {/* Papers List */}
            <div className="space-y-4">
                {papers.map((paper, index) => (
                    <div key={index} className="glass-card p-6 hover:border-[var(--primary)] transition-colors">
                        <div className="flex items-start justify-between gap-4">
                            <div className="flex-1">
                                <h3 className="font-semibold text-lg leading-tight">
                                    {paper.title}
                                </h3>
                                <div className="flex items-center gap-4 mt-2 text-sm text-[var(--muted)]">
                                    <span className="flex items-center gap-1">
                                        <Users className="w-4 h-4" />
                                        {paper.authors}
                                    </span>
                                    <span className="flex items-center gap-1">
                                        <BookOpen className="w-4 h-4" />
                                        {paper.venue}
                                    </span>
                                    <span className="flex items-center gap-1">
                                        <Calendar className="w-4 h-4" />
                                        {paper.year}
                                    </span>
                                </div>
                                <p className="mt-3 text-sm text-[var(--muted)] leading-relaxed">
                                    {paper.abstract}
                                </p>
                                <div className="flex items-center gap-2 mt-3 flex-wrap">
                                    {paper.tags.map((tag) => (
                                        <span
                                            key={tag}
                                            className={`px-2 py-0.5 rounded-full text-xs ${tagColors[tag] || "bg-gray-500/20 text-gray-300"
                                                }`}
                                        >
                                            <Tag className="w-3 h-3 inline mr-1" />
                                            {tag}
                                        </span>
                                    ))}
                                </div>
                            </div>
                            {paper.arxivId && (
                                <a
                                    href={`https://arxiv.org/abs/${paper.arxivId}`}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="px-4 py-2 bg-[var(--primary)] text-white rounded-lg hover:bg-[var(--primary-hover)] transition-colors flex items-center gap-2 text-sm whitespace-nowrap"
                                >
                                    <ExternalLink className="w-4 h-4" />
                                    arXiv
                                </a>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Call to Action */}
            <div className="glass-card p-6 text-center">
                <h3 className="font-semibold text-lg mb-2">贡献更多论文</h3>
                <p className="text-[var(--muted)] text-sm mb-4">
                    发现了相关的 Conversational AI 论文？欢迎通过 GitHub 提交 PR！
                </p>
                <a
                    href="https://github.com/Coowoolf/paperhunt"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="btn-primary inline-flex items-center gap-2"
                >
                    <ExternalLink className="w-4 h-4" />
                    访问 GitHub
                </a>
            </div>
        </div>
    );
}
